### ISSUE TITLE
Remove mention of digital signatures

### ISSUE THREAD

**Issue by hlflanagan** [rfc-format/draft-iab-rfc-use-of-pdf-bis#1]
Given we will not be digitally signing RFCs in the foreseeable future, we should go ahead and remove Section 3.3. Digital Signatures

**Comment by masinter** [comment]
i missed the discussion -- why not ?

**Comment by TonyLHansen** [comment]
subsumed by subsequent discussion where that section was rewritten to provide guidance about signing for I-Ds and RFCs
